version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      -  ${MONGO_DATA}:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
  webhook:
    image: ionburger/stravasheetsync-webhook:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      MONGO_HOST: mongodb
      MONGO_PORT: 27017

