services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      -  ${MONGO_DATA}:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
  webhook:
    image: ionburger/stravasheetsync-webhook:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    expose:
      - 8080:8080
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      STRAVA_ID: ${STRAVA_ID}
      STRAVA_SECRET: ${STRAVA_SECRET}
      GOOGLE_ID: ${GOOGLE_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
    volumes:
      - ../webhook:/code